# Generated by Django 2.1.1 on 2018-10-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_termino', models.DateTimeField(verbose_name='Data de Término')),
                ('descricao', models.CharField(max_length=500)),
                ('publico_privado', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PU', max_length=2)),
                ('local', models.CharField(max_length=100)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='SubEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('gratis', models.BooleanField(verbose_name='Grátis')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('inicio_vendas', models.DateTimeField(verbose_name='Início das vendas')),
                ('termino_vendas', models.DateTimeField(verbose_name='Término das vendas')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingressos.Evento')),
            ],
            options={
                'verbose_name': 'SubEvento',
                'verbose_name_plural': 'SubEventos',
            },
        ),
        migrations.CreateModel(
            name='SubEventoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de SubEvento',
                'verbose_name_plural': 'Tipos de SubEventos',
            },
        ),
        migrations.CreateModel(
            name='TipoIngresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Ingresso',
                'verbose_name_plural': 'Tipos de Ingressos',
            },
        ),
        migrations.AddField(
            model_name='subevento',
            name='subeventotipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingressos.SubEventoTipo'),
        ),
        migrations.AddField(
            model_name='subevento',
            name='tipoingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingressos.TipoIngresso'),
        ),
    ]
