# Generated by Django 2.1.2 on 2018-10-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.BooleanField(default=False),
        ),
    ]
