# Generated by Django 2.1.2 on 2018-10-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0002_evento_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='absorver_taxa_servico',
            field=models.BooleanField(default=False),
        ),
    ]
