# Generated by Django 2.1.2 on 2018-10-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0003_evento_absorver_taxa_servico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubEvento',
            new_name='Ingresso',
        ),
    ]
